explain: |md
  # Overview
  This is root file with an overview of other diagrams.
| {
  near: top-center
}

grid-columns: 2

c4: C4 - Context diagram {
  link: layers.c4
}

layers: {
  c4: {...@context}
}
