explain: |md
  C1: This is the second layer, a bit more detailed. Click this to go back: ...
| {
  near: top-center
  link: _
}

user: User {
  shape: person
}
internal_system: Internal system
external_system: External system
user -> internal_system: Uses

frontend: Frontend
bff: Backend for frontend
sub_system1: Sub system 1 (proxy)
sub_system2: Sub system 2
sub_system3: Sub system 3

user -> frontend: Uses
frontend -> bff: Depends on

bff -> sub_system1: Depends on
bff -> sub_system2: Depends on
bff -> sub_system3: Depends on

sub_system1 -> internal_system: Depends on
sub_system2 -> external_system: Depends on

layers: {
  subsystem1: {
    frontend: Frontend
    bff: Backend for frontend
    internal_system: Internal system
  }
}
