classes: {
  dot: {
    style.fill: black
    shape: circle
    height: 10
    width: 10
    style.border-radius: 16
  }

  choice: {
    shape: diamond
    label: ""
    height: 30
    width: 30
  }

  s3: {
    shape: image
    icon: https://icons.terrastruct.com/aws/Storage/Amazon-Simple-Storage-Service-S3.svg
  }

  ddb: {
    shape: image
    icon: https://icons.terrastruct.com/essentials/117-database.svg
  }

  service: {
    shape: hexagon
    style: {
      stroke-width: 4
    }
  }

  problem: {
    style: {
      stroke: orangered
      stroke-dash: 3
    }
  }
}
